[package]
name = "patched-porobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.140"
serde_json = "1.0.82"
teloxide = "0.10.1"
tokio = { version =  "1.20.1", features = ["rt-multi-thread", "macros"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
glob = "0.3.0"
itertools = "0.10.2"
