[package]
name = "patched-porobot"
version = "0.1.0"
authors = ["Stefano Pigozzi <me@steffo.eu>"]
edition = "2021"
description = "Legends of Runeterra card database utilities and bots"
repository = "https://github.com/Steffo99/patched-porobot"
license = "AGPL-3.0-or-later"
keywords = ["game", "deserialization", "legends-of-runeterra", "bot", "search"]
categories = ["games", "parser-implementations"]

[dependencies]
serde = "1.0.140"
serde_json = "1.0.82"
teloxide = "0.10.1"
tokio = { version =  "1.20.1", features = ["rt-multi-thread", "macros"] }
log = "0.4.17"
pretty_env_logger = "0.4.0"
glob = "0.3.0"
itertools = "0.10.2"
tantivy = "0.18.0"
reqwest = "0.11.11"