# To be used in Portainer
# Requires https://hub.docker.com/r/mochoa/s3fs-volume-plugin to be installed

version: "3.9"

services:
  telegram:
    image: "ghcr.io/steffo99/patched-porobot:latest"
    command: "patched_porobot_telegram"
    restart: unless-stopped
    volumes:
      - "$PORO_CARDS_DIR:/usr/src/patched_porobot/data"
    env_file:
      - stack.env
    # deploy:
    #   resources:
    #     limits:
    #       memory: 16M
